namespace SpiderClientConverter
{
    enum AppearanceFlag1000 : byte
    {
        Ground = 0,
        Clip = 1,
        Bottom = 2,
        Top = 3,
        Container = 4,
        Stackable = 5,
        ForceUse = 6,
        Usable = 254,
        MltiUse = 7,
        Writeable = 8,
        WriteableOnce = 9,
        LiquidContainer = 10,
        LiquidPool = 11,
        Impassable = 12,
        Unmovable = 13,
        BlocksSight = 14,
        BlocksPathfinding = 15,
        NoMovementAnimation = 16,
        Pickupable = 17,
        Hangable = 18,
        HooksSouth = 19,
        HooksEast = 20,
        Rotateable = 21,
        LightSource = 22,
        AlwaysSeen = 23,
        Translucent = 24,
        Displaced = 25,
        Elevated = 26,
        LyingObject = 27,
        AlwaysAnimated = 28,
        MinimapColor = 29,
        HelpInfo = 30,
        FullTile = 31,
        Lookthrough = 32,
        Clothes = 33,
        Market = 34,
        DefaultAction = 35,
        Wrappable = 36,
        UnWrappable = 37,
        TopEffect = 38,
        NpcSaleData = 39,
        ChangedToExpire = 40,
        Corpse = 41,
        PlayerCorpse = 42,
        CyclopediaItem = 43,
        Ammo = 44,
        ShowOffSocket = 45,
        Reportable = 46,
        UpgradeClassification = 47,
        Wearout = 48,
        ClockExpire = 49,
        Expire = 50,
        ExpireStop = 51,
        Default = 255

    }
}

